"use client";
import { useEffect, useState } from "react";
import { createApiClient } from "@/services/api-client";
interface InvitationTask { readonly id: string; readonly name: string; readonly status: string; readonly userCount: number; readonly accountIds: readonly string[]; }
interface Account { readonly id: string; readonly username?: string | null; readonly status: string; }
function fileToBase64(file: File): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",").pop() ?? ""); reader.onerror = () => reject(reader.error ?? new Error("file_read_failed")); reader.readAsDataURL(file); }); }
export default function InvitationsPage() { const [items, setItems] = useState<readonly InvitationTask[]>([]); const [name, setName] = useState(""); const [target, setTarget] = useState(""); const [accountId, setAccountId] = useState(""); const [status, setStatus] = useState<string>();
  const [accounts, setAccounts] = useState<readonly Account[]>([]); const [file, setFile] = useState<File | null>(null); const api = createApiClient();
  async function load() { try { const [tasks, owned] = await Promise.all([api.get<{ readonly items: readonly InvitationTask[] }>("/api/invitations/tasks"), api.get<{ readonly items: readonly Account[] }>("/api/accounts")]); setItems(tasks.items); setAccounts(owned.items); if (!accountId && owned.items[0]) setAccountId(owned.items[0].id); } catch (error) { setStatus(error instanceof Error ? error.message : "Не удалось загрузить данные."); } }
  useEffect(() => { void load(); }, []);
  async function create() { if (!name.trim() || !target.trim() || !accountId || !file) { setStatus("Укажите название, chat UUID, аккаунт и Excel/CSV файл"); return; } try { const task = await api.post<{ readonly task: { readonly id: string } }>("/api/invitations/tasks", { name: name.trim(), target: { chatId: target.trim() }, accountIds: [accountId] }); const encoded = await fileToBase64(file); const result = await api.post<{ readonly preview: { readonly valid: number; readonly invalid: number; readonly duplicates: number } }>("/api/invitations/import", { taskId: task.task.id, filename: file.name, fileBase64: encoded }); setStatus("Импортировано строк: " + result.preview.valid + "; ошибок: " + result.preview.invalid + "; дубликатов: " + result.preview.duplicates); setFile(null); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "Импорт не удался."); } }
  return <div className="space-y-6"><div><p className="eyebrow">Telegram / Invitations</p><h1 className="mt-2 text-3xl font-semibold text-white">Приглашения</h1><p className="mt-3 text-sm leading-6 text-slate-400">Создайте задачу, выберите принадлежащий вам аккаунт и загрузите XLSX/CSV с колонкой username. Каждая строка валидируется отдельно.</p></div><section className="surface-card grid gap-3 p-5 sm:grid-cols-2"><label className="text-xs text-slate-400">Название<input value={name} onChange={event => setName(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-white" /></label><label className="text-xs text-slate-400">UUID целевого чата<input value={target} onChange={event => setTarget(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-white" /></label><label className="text-xs text-slate-400">Telegram аккаунт<select value={accountId} onChange={event => setAccountId(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-white"><option value="">Выберите аккаунт</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.username ? "@" + account.username : account.id} · {account.status}</option>)}</select></label><label className="text-xs text-slate-400">Excel или CSV<input type="file" accept=".xlsx,.xls,.csv" onChange={event => setFile(event.target.files?.[0] ?? null)} className="mt-1 block min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-300" /></label><button type="button" onClick={() => void create()} className="min-h-11 rounded-lg bg-emerald-300 px-4 text-sm font-semibold text-slate-950 sm:col-span-2">Создать задачу и импортировать</button>{status ? <p role="status" className="text-sm text-slate-400 sm:col-span-2">{status}</p> : null}</section><section className="surface-card divide-y divide-slate-800">{items.length === 0 ? <p className="p-6 text-sm text-slate-500">Задач пока нет.</p> : items.map(task => <article key={task.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><h2 className="font-medium text-slate-200">{task.name}</h2><p className="text-xs text-slate-500">{task.status} · {task.userCount} пользователей · {task.accountIds.length} аккаунтов</p></div></article>)}</section></div>; }
