"use client";
import { useState } from "react";
import { createApiClient } from "@/services/api-client";
interface Task { readonly id: string; readonly name: string; readonly type: string; readonly status: string; readonly accountIds: readonly string[]; }
export default function TasksPage() { const [items, setItems] = useState<readonly Task[]>([]); const [name, setName] = useState(""); const [status, setStatus] = useState<string>();
  async function load() { try { const result = await createApiClient().get<{ readonly items: readonly Task[] }>("/api/tasks"); setItems(result.items); } catch (error) { setStatus(error instanceof Error ? error.message : "Не удалось загрузить задачи."); } }
  async function create() { if (!name.trim()) return; try { await createApiClient().post("/api/tasks", { name: name.trim(), type: "PROCESS_TASK", accountIds: [] }); setName(""); setStatus("Задача создана"); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "Не удалось создать задачу."); } }
  async function queue(task: Task) { try { const result = await createApiClient().post<{ readonly jobId: string }>(`/api/tasks/${task.id}/queue`, {}); setStatus(`Задача поставлена в очередь: ${result.jobId}`); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "Не удалось поставить задачу в очередь."); } }
  return <div className="space-y-6"><div><p className="eyebrow">Operations / Tasks</p><h1 className="mt-2 text-3xl font-semibold text-white">Задачи</h1><p className="mt-3 text-sm text-slate-400">Задачи сохраняются в PostgreSQL и запускаются через очередь worker.</p></div><section className="surface-card flex flex-wrap gap-3 p-5"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Название задачи" className="min-h-11 min-w-64 flex-1 rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-white" /><button type="button" onClick={() => void create()} className="min-h-11 rounded-lg bg-emerald-300 px-4 text-sm font-semibold text-slate-950">Создать</button><button type="button" onClick={() => void load()} className="min-h-11 rounded-lg border border-slate-700 px-4 text-sm text-slate-200">Обновить</button>{status ? <p role="status" className="w-full text-sm text-slate-400">{status}</p> : null}</section><section className="surface-card overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Название</th><th className="p-4">Тип</th><th className="p-4">Статус</th><th className="p-4">Аккаунты</th><th className="p-4">Действие</th></tr></thead><tbody className="divide-y divide-slate-800">{items.map((task) => <tr key={task.id}><td className="p-4 text-slate-200">{task.name}</td><td className="p-4 text-slate-400">{task.type}</td><td className="p-4 text-slate-400">{task.status}</td><td className="p-4 text-slate-500">{task.accountIds.length}</td><td className="p-4">{["DRAFT", "PAUSED", "FAILED"].includes(task.status) ? <button type="button" onClick={() => void queue(task)} className="rounded border border-emerald-300/40 px-3 py-1.5 text-xs text-emerald-200">В очередь</button> : null}</td></tr>)}</tbody></table></section></div>; }
