import type { IncomingMessage, ServerResponse } from "node:http";
import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import type { RoleName, TelegramAccountStatus, ProxyProtocol, ChatType, TaskStatus, TaskType, Prisma, LogLevel, LogType } from "@prisma/client";
import { z } from "zod";
import { can, hashPassword, verifyPassword, type ApiSecurity, type PasswordResetMessage, type PasswordResetNotifier } from "./security.js";
import type { ApiStore, StoredAccount, StoredChat, StoredContact, StoredInvitationImport, StoredInvitationTask, StoredMessage, StoredProxy, StoredTask, StoredUser, StoredLog, StoredAuditLog } from "./store.js";
import { parseInvitationImport } from "./invitation-import.js";
import { NetworkProxyChecker, parseProxyLine, type ProxyChecker, type ProxyCheckResult } from "./proxy-manager.js";
import { createCommandEnvelope, type CommandQueuePort } from "../queues/command-queue.js";
import type { EventHub } from "../realtime/event-hub.js";

const roles = ["OWNER", "ADMIN", "OPERATOR", "VIEWER"] as const;
const accountStatuses = ["ONLINE", "OFFLINE", "CONNECTING", "FLOOD_WAIT", "UNAUTHORIZED", "PROXY_ERROR", "TELEGRAM_ERROR", "DISABLED"] as const;
const proxyProtocols = ["SOCKS5", "HTTP", "HTTPS"] as const;
const JSON_HEADERS = { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" };
const registerSchema = z.object({ email: z.string().email(), name: z.string().trim().min(1).max(120).optional(), password: z.string().min(12).max(200) });
const loginSchema = z.object({ email: z.string().email(), password: z.string().min(1) });
const userSchema = registerSchema.extend({ role: z.enum(roles).default("VIEWER") });
const accountSchema = z.object({ telegramId: z.string().regex(/^[-]?\d+$/).optional(), username: z.string().trim().min(1).max(120).optional(), phone: z.string().trim().max(40).optional(), firstName: z.string().trim().max(120).optional(), lastName: z.string().trim().max(120).optional(), avatarUrl: z.string().url().optional(), proxyId: z.string().uuid().optional() });
const proxySchema = z.object({ name: z.string().trim().min(1).max(120), host: z.string().trim().min(1).max(255), port: z.number().int().min(1).max(65535), protocol: z.enum(proxyProtocols), username: z.string().max(255).optional(), password: z.string().max(255).optional(), country: z.string().trim().max(8).optional() });

function publicUser(user: StoredUser) { return { id: user.id, email: user.email, name: user.name, roles: user.roles, createdAt: user.createdAt.toISOString(), updatedAt: user.updatedAt.toISOString() }; }
function maskPhone(phone: string | null): string | null { if (!phone) return null; if (phone.length <= 4) return "*".repeat(phone.length); return `${phone.slice(0, 2)}${"*".repeat(Math.max(1, phone.length - 5))}${phone.slice(-2)}`; }
function publicAccount(account: StoredAccount, proxy?: StoredProxy) { return { id: account.id, ownerId: account.ownerId, telegramId: account.telegramId?.toString() ?? null, username: account.username, phone: maskPhone(account.phone), firstName: account.firstName, lastName: account.lastName, avatarUrl: account.avatarUrl, status: account.status, lastOnlineAt: account.lastOnlineAt?.toISOString() ?? null, lastActivityAt: account.lastActivityAt?.toISOString() ?? null, sessionStatus: account.sessionStatus, errorState: account.errorState, proxy: proxy ? { id: proxy.id, name: proxy.name, host: proxy.host, port: proxy.port, protocol: proxy.protocol, country: proxy.country, status: proxy.status, pingMs: proxy.pingMs } : null } as const; }
function publicProxy(proxy: StoredProxy) { return { id: proxy.id, name: proxy.name, host: proxy.host, port: proxy.port, protocol: proxy.protocol, country: proxy.country, pingMs: proxy.pingMs, status: proxy.status, lastCheckedAt: proxy.lastCheckedAt?.toISOString() ?? null, errorCode: proxy.errorCode, disabledAt: proxy.disabledAt?.toISOString() ?? null, createdAt: proxy.createdAt.toISOString(), updatedAt: proxy.updatedAt.toISOString(), hasUsername: proxy.encryptedUsername !== null, hasPassword: proxy.encryptedPassword !== null }; }
function publicChat(chat: StoredChat) { return { id: chat.id, telegramAccountId: chat.telegramAccountId, telegramId: chat.telegramId.toString(), type: chat.type, title: chat.title, username: chat.username, avatarUrl: chat.avatarUrl, lastMessageAt: chat.lastMessageAt?.toISOString() ?? null, unreadCount: chat.unreadCount, muted: chat.muted, pinned: chat.pinned, createdAt: chat.createdAt.toISOString(), updatedAt: chat.updatedAt.toISOString() }; }
function publicMessage(message: StoredMessage) { return { id: message.id, chatId: message.chatId, telegramId: message.telegramId.toString(), senderId: message.senderId?.toString() ?? null, body: message.body, mediaType: message.mediaType, sentAt: message.sentAt.toISOString(), editedAt: message.editedAt?.toISOString() ?? null, replyToId: message.replyToId?.toString() ?? null, metadata: message.metadata }; }
function maskContactPhone(phone: string | null): string | null { return maskPhone(phone); }
function publicContact(contact: StoredContact) { return { id: contact.id, telegramAccountId: contact.telegramAccountId, telegramId: contact.telegramId.toString(), firstName: contact.firstName, lastName: contact.lastName, username: contact.username, phone: maskContactPhone(contact.phone), source: contact.source, notes: contact.notes, tags: contact.tags, createdAt: contact.createdAt.toISOString(), updatedAt: contact.updatedAt.toISOString() }; }
function publicTask(task: StoredTask) { return { id: task.id, createdById: task.createdById, name: task.name, type: task.type, status: task.status, target: task.target, source: task.source, progress: task.progress, error: task.error, accountIds: task.accountIds, startedAt: task.startedAt?.toISOString() ?? null, completedAt: task.completedAt?.toISOString() ?? null, createdAt: task.createdAt.toISOString(), updatedAt: task.updatedAt.toISOString() }; }
function publicInvitationTask(task: StoredInvitationTask) { return { id: task.id, createdById: task.createdById, name: task.name, status: task.status, target: task.target, scheduleAt: task.scheduleAt?.toISOString() ?? null, notes: task.notes, accountIds: task.accountIds, userCount: task.userCount, createdAt: task.createdAt.toISOString(), updatedAt: task.updatedAt.toISOString() }; }
function publicInvitationImport(item: StoredInvitationImport) { return { id: item.id, invitationTaskId: item.invitationTaskId, uploadedById: item.uploadedById, filename: item.filename, totalRows: item.totalRows, validRows: item.validRows, invalidRows: item.invalidRows, duplicateRows: item.duplicateRows, createdAt: item.createdAt.toISOString() }; }
const SECRET_KEYS = new Set(["password", "passwordHash", "token", "refreshToken", "accessToken", "session", "sessionString", "encryptedArchive", "encryptedUsername", "encryptedPassword", "apiHash", "apiKey", "secret"]);
function redact(value: unknown): unknown { if (Array.isArray(value)) return value.map(redact); if (value && typeof value === "object") { const output: Record<string, unknown> = {}; for (const [key, child] of Object.entries(value)) output[key] = SECRET_KEYS.has(key) ? "[REDACTED]" : redact(child); return output; } return value; }
function publicLog(log: StoredLog) { return { id: log.id, type: log.type, level: log.level, telegramAccountId: log.telegramAccountId, proxyId: log.proxyId, workerId: log.workerId, taskId: log.taskId, action: log.action, description: log.description, errorCode: log.errorCode, metadata: redact(log.metadata), createdAt: log.createdAt.toISOString() }; }
function publicAuditLog(log: StoredAuditLog) { return { id: log.id, actorId: log.actorId, role: log.role, ipAddress: log.ipAddress, action: log.action, entity: log.entity, entityId: log.entityId, before: redact(log.before), after: redact(log.after), metadata: redact(log.metadata), createdAt: log.createdAt.toISOString() }; }
function encrypt(value: string, key: Buffer): string { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key, iv); const payload = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${payload.toString("base64url")}`; }
function decrypt(value: string | null, key: Buffer): string | undefined { if (value === null) return undefined; const [iv, tag, payload] = value.split("."); if (!iv || !tag || !payload) return undefined; const decipher = createDecipheriv("aes-256-gcm", key, Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return Buffer.concat([decipher.update(Buffer.from(payload, "base64url")), decipher.final()]).toString("utf8"); }
async function body(request: IncomingMessage): Promise<unknown> { const chunks: Buffer[] = []; for await (const chunk of request) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)); if (chunks.length === 0) return {}; try { return JSON.parse(Buffer.concat(chunks).toString("utf8")); } catch { throw new Error("INVALID_JSON"); } }
function write(response: ServerResponse, status: number, value?: unknown): void { response.writeHead(status, JSON_HEADERS); response.end(value === undefined ? undefined : JSON.stringify(value)); }
function pathParts(request: IncomingMessage): { path: string; query: URLSearchParams } { const url = new URL(request.url ?? "/", "http://backend.local"); return { path: url.pathname, query: url.searchParams }; }

export interface ApiControllerOptions { readonly store: ApiStore; readonly security: ApiSecurity; readonly passwordResetNotifier: PasswordResetNotifier; readonly proxyChecker?: ProxyChecker | undefined; readonly commandQueue: CommandQueuePort; readonly eventHub?: EventHub; }

export class ApiController {
  public constructor(private readonly options: ApiControllerOptions) {}
  public async handle(request: IncomingMessage, response: ServerResponse): Promise<void> {
    try {
      const { path, query } = pathParts(request); const method = (request.method ?? "GET").toUpperCase();
      if (path === "/api/openapi.json" && method === "GET") {
        write(response, 200, { openapi: "3.0.0", info: { title: "Invait Telegram VDS API", version: "0.1.0" }, paths: { "/api/auth/login": {}, "/api/users": {}, "/api/users/{id}": {}, "/api/accounts": {}, "/api/chats": {}, "/api/messages": {}, "/api/contacts": {}, "/api/tasks": {}, "/api/invitations/tasks": {}, "/api/invitations/import": {}, "/api/proxies": {}, "/api/logs": { get: { summary: "List owned operational logs", parameters: ["type", "level", "accountId", "taskId", "search", "limit", "before"] } }, "/api/audit": { get: { summary: "List immutable audit records", parameters: ["entity", "search", "limit", "before"] } } } });
        return;
      }
      if (path.startsWith("/api/auth/")) { await this.auth(method, path.slice(10), request, response); return; }
      const user = await this.currentUser(request); if (!user) { write(response, 401, { error: "authentication_required" }); return; }
      if (path === "/api/events" && method === "GET" && this.options.eventHub) {
        response.writeHead(200, { "Content-Type": "text/event-stream; charset=utf-8", "Cache-Control": "no-cache", Connection: "keep-alive", "X-Accel-Buffering": "no" });
        response.write(`event: ready\ndata: ${JSON.stringify({ userId: user.id })}\n\n`);
        const subscription = this.options.eventHub.subscribe((event) => response.write(`event: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`));
        request.on("close", () => subscription.close());
        return;
      }
      if (path === "/api/system" && method === "GET") {
        if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" });
        const memory = process.memoryUsage();
        return write(response, 200, { nodeEnv: process.env.NODE_ENV ?? "development", uptimeSeconds: Math.floor(process.uptime()), memory: { rss: memory.rss, heapUsed: memory.heapUsed, heapTotal: memory.heapTotal }, eventSubscribers: this.options.eventHub?.size ?? 0, now: new Date().toISOString() });
      }
      if (method === "POST") {
        const invitationTaskId = path.match(/^\/api\/invitations\/tasks\/([^/]+)\/queue$/)?.[1];
        const taskAction = path.match(/^\/api\/tasks\/([^/]+)\/(queue|cancel)$/);
        if (path === "/api/invitations/tasks") await this.audit(user, request, "CREATE", "InvitationTask");
        else if (path === "/api/invitations/import") await this.audit(user, request, "IMPORT", "InvitationImport");
        else if (path === "/api/accounts/import-tdata") await this.audit(user, request, "IMPORT", "TData");
        else if (invitationTaskId) await this.audit(user, request, "QUEUE", "InvitationTask", invitationTaskId);
        else if (taskAction?.[1] && taskAction[2]) await this.audit(user, request, taskAction[2] === "queue" ? "QUEUE" : "CANCEL", "Task", taskAction[1]);
      }
      if (path === "/api/accounts/import-tdata" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const parsed = z.object({ filename: z.string().trim().min(1).max(255), archiveBase64: z.string().min(1).max(35_000_000), proxyId: z.string().uuid().optional(), accountGroupId: z.string().uuid().optional() }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); if (!parsed.data.filename.toLowerCase().endsWith(".zip") || parsed.data.filename.includes("/") || parsed.data.filename.includes("\\")) return write(response, 400, { error: "invalid_filename" }); const encoded = parsed.data.archiveBase64; if (!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded) || encoded.length % 4 === 1) return write(response, 400, { error: "invalid_archive" }); let archive: Buffer; try { archive = Buffer.from(encoded, "base64"); } catch { return write(response, 400, { error: "invalid_archive" }); } if (archive.length === 0 || archive.length > 25 * 1024 * 1024) return write(response, 400, { error: "invalid_archive" }); if (parsed.data.proxyId && !(await this.options.store.findProxy(parsed.data.proxyId))) return write(response, 400, { error: "proxy_not_found" }); const command = createCommandEnvelope({ type: "IMPORT_TDATA", requestedBy: user.id, payload: { filename: parsed.data.filename, encryptedArchive: encrypt(archive.toString("base64"), this.securityKey), proxyId: parsed.data.proxyId, accountGroupId: parsed.data.accountGroupId } }); const receipt = await this.options.commandQueue.enqueue(command); return write(response, 202, { jobId: receipt.jobId, status: "QUEUED" }); }
      if (path === "/api/chats" && method === "GET") { if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" }); const accountId = query.get("accountId") ?? undefined; const account = accountId === undefined ? undefined : await this.options.store.findAccount(accountId); if (accountId !== undefined && (!account || account.ownerId !== user.id)) return write(response, 404, { error: "not_found" }); const typeValue = query.get("type") ?? undefined; const type = typeValue && ["PRIVATE", "GROUP", "SUPERGROUP", "CHANNEL"].includes(typeValue) ? typeValue as ChatType : undefined; const items = await this.options.store.listChats(user.id, { ...(accountId === undefined ? {} : { accountId }), ...(type === undefined ? {} : { type }), ...(query.get("search") ? { search: query.get("search")! } : {}) }); return write(response, 200, { items: items.map(publicChat) }); }
      if (path === "/api/chats/sync" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const accountId = query.get("accountId") ?? undefined; const account = await this.options.store.findAccount(accountId); if (!account || account.ownerId !== user.id) return write(response, 404, { error: "not_found" }); const command = createCommandEnvelope({ type: "LOAD_DIALOGS", accountId: account.id, requestedBy: user.id, payload: {} }); const receipt = await this.options.commandQueue.enqueue(command); return write(response, 202, { jobId: receipt.jobId, status: "QUEUED" }); }
      if (path === "/api/messages" && method === "GET") { if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" }); const chatId = query.get("chatId"); if (!chatId) return write(response, 400, { error: "chat_id_required" }); const chat = await this.options.store.findChat(chatId); const account = chat ? await this.options.store.findAccount(chat.telegramAccountId) : undefined; if (!chat || !account || account.ownerId !== user.id) return write(response, 404, { error: "not_found" }); const rawLimit = Number(query.get("limit") ?? "50"); const limit = Number.isInteger(rawLimit) && rawLimit > 0 ? Math.min(rawLimit, 100) : 50; const beforeValue = query.get("before"); const before = beforeValue && /^-?\d+$/.test(beforeValue) ? BigInt(beforeValue) : undefined; const items = await this.options.store.listMessages(chat.id, { limit, ...(before === undefined ? {} : { before }) }); const nextCursor = items.length === limit ? items.at(-1)?.telegramId.toString() ?? null : null; return write(response, 200, { items: items.map(publicMessage), nextCursor }); }
      if (path === "/api/messages/sync" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const chatId = query.get("chatId"); const chat = chatId ? await this.options.store.findChat(chatId) : undefined; const account = chat ? await this.options.store.findAccount(chat.telegramAccountId) : undefined; if (!chat || !account || account.ownerId !== user.id) return write(response, 404, { error: "not_found" }); const command = createCommandEnvelope({ type: "LOAD_MESSAGES", accountId: account.id, requestedBy: user.id, payload: { chatId: chat.id, limit: 50 } }); const receipt = await this.options.commandQueue.enqueue(command); return write(response, 202, { jobId: receipt.jobId, status: "QUEUED" }); }
      if (path === "/api/messages" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const parsed = z.object({ chatId: z.string().uuid(), text: z.string().trim().min(1).max(4096), replyToId: z.string().regex(/^\d+$/).optional() }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); const chat = await this.options.store.findChat(parsed.data.chatId); const account = chat ? await this.options.store.findAccount(chat.telegramAccountId) : undefined; if (!chat || !account || account.ownerId !== user.id) return write(response, 404, { error: "not_found" }); const command = createCommandEnvelope({ type: "SEND_MESSAGE", accountId: account.id, requestedBy: user.id, payload: { chatId: chat.id, text: parsed.data.text, ...(parsed.data.replyToId === undefined ? {} : { replyToId: parsed.data.replyToId }) } }); const receipt = await this.options.commandQueue.enqueue(command); return write(response, 202, { jobId: receipt.jobId, status: "QUEUED" }); }
      if (path === "/api/contacts" && method === "GET") { if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" }); const accountId = query.get("accountId") ?? undefined; const account = accountId === undefined ? undefined : await this.options.store.findAccount(accountId); if (accountId !== undefined && (!account || account.ownerId !== user.id)) return write(response, 404, { error: "not_found" }); const rawLimit = Number(query.get("limit") ?? "50"); const limit = Number.isInteger(rawLimit) && rawLimit > 0 ? Math.min(rawLimit, 100) : 50; const beforeValue = query.get("before"); const before = beforeValue && /^-?\d+$/.test(beforeValue) ? BigInt(beforeValue) : undefined; const items = await this.options.store.listContacts(user.id, { ...(accountId === undefined ? {} : { accountId }), ...(query.get("search") ? { search: query.get("search")! } : {}), limit, ...(before === undefined ? {} : { before }) }); return write(response, 200, { items: items.map(publicContact), nextCursor: items.length === limit ? items.at(-1)?.telegramId.toString() ?? null : null }); }
      if (path === "/api/contacts/sync" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const accountId = query.get("accountId") ?? undefined; const account = await this.options.store.findAccount(accountId); if (!account || account.ownerId !== user.id) return write(response, 404, { error: "not_found" }); const command = createCommandEnvelope({ type: "LOAD_CONTACTS", accountId: account.id, requestedBy: user.id, payload: {} }); const receipt = await this.options.commandQueue.enqueue(command); return write(response, 202, { jobId: receipt.jobId, status: "QUEUED" }); }
      if (path === "/api/tasks" && method === "GET") { if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" }); const statusValue = query.get("status"); const statuses = ["DRAFT", "QUEUED", "RUNNING", "PAUSED", "COMPLETED", "FAILED", "CANCELLED"] as const; const status = statusValue && (statuses as readonly string[]).includes(statusValue) ? statusValue as TaskStatus : undefined; return write(response, 200, { items: (await this.options.store.listTasks(user.id, { ...(status === undefined ? {} : { status }) })).map(publicTask) }); }
      if (path === "/api/tasks" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const taskTypes = ["CONNECT_ACCOUNT", "DISCONNECT_ACCOUNT", "SEND_MESSAGE", "LOAD_DIALOGS", "LOAD_MESSAGES", "LOAD_CONTACTS", "CHANGE_PROXY", "IMPORT_TDATA", "PROCESS_TASK", "PROCESS_INVITATION_ITEM", "HEALTH_CHECK"] as const; const parsed = z.object({ name: z.string().trim().min(1).max(160), type: z.enum(taskTypes), accountIds: z.array(z.string().uuid()).max(100).default([]), target: z.record(z.unknown()).optional(), source: z.record(z.unknown()).optional() }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); for (const accountId of parsed.data.accountIds) { const account = await this.options.store.findAccount(accountId); if (!account || account.ownerId !== user.id) return write(response, 400, { error: "account_not_available" }); } const task = await this.options.store.createTask({ createdById: user.id, name: parsed.data.name, type: parsed.data.type as TaskType, accountIds: parsed.data.accountIds, ...(parsed.data.target === undefined ? {} : { target: parsed.data.target as Prisma.InputJsonValue }), ...(parsed.data.source === undefined ? {} : { source: parsed.data.source as Prisma.InputJsonValue }) }); await this.audit(user, request, "CREATE", "Task", task.id, undefined, publicTask(task)); return write(response, 201, { task: publicTask(task) }); }
      const taskAction = path.match(/^\/api\/tasks\/([^/]+)\/(queue|cancel)$/); if (taskAction && method === "POST") { const taskId = taskAction[1]; const action = taskAction[2]; if (!taskId || !action) return write(response, 404, { error: "not_found" }); if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const task = await this.options.store.findTask(taskId); if (!task || task.createdById !== user.id) return write(response, 404, { error: "not_found" }); if (action === "cancel") { const cancelled = await this.options.store.updateTask(task.id, { status: "CANCELLED", completedAt: new Date() }); return write(response, 200, { task: publicTask(cancelled) }); } if (!["DRAFT", "PAUSED", "FAILED"].includes(task.status)) return write(response, 409, { error: "task_not_queueable" }); const queued = await this.options.store.updateTask(task.id, { status: "QUEUED", error: null }); const command = createCommandEnvelope({ type: "PROCESS_TASK", requestedBy: user.id, payload: { taskId: task.id } }); const receipt = await this.options.commandQueue.enqueue(command); return write(response, 202, { task: publicTask(queued), jobId: receipt.jobId }); }
      if (path === "/api/invitations/tasks" && method === "GET") { if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" }); return write(response, 200, { items: (await this.options.store.listInvitationTasks(user.id)).map(publicInvitationTask) }); }
      if (path === "/api/invitations/tasks" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const parsed = z.object({ name: z.string().trim().min(1).max(160), target: z.object({ chatId: z.string().uuid() }), accountIds: z.array(z.string().uuid()).min(1).max(100), scheduleAt: z.string().datetime().optional(), notes: z.string().max(2000).optional() }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); const targetChat = await this.options.store.findChat(parsed.data.target.chatId); if (!targetChat || targetChat.type === "PRIVATE") return write(response, 400, { error: "target_chat_not_allowed" }); for (const accountId of parsed.data.accountIds) { const account = await this.options.store.findAccount(accountId); if (!account || account.ownerId !== user.id || account.id !== targetChat.telegramAccountId) return write(response, 400, { error: "account_not_available" }); } const task = await this.options.store.createInvitationTask({ createdById: user.id, name: parsed.data.name, target: parsed.data.target as Prisma.InputJsonValue, accountIds: parsed.data.accountIds, ...(parsed.data.scheduleAt === undefined ? {} : { scheduleAt: new Date(parsed.data.scheduleAt) }), ...(parsed.data.notes === undefined ? {} : { notes: parsed.data.notes }) }); return write(response, 201, { task: publicInvitationTask(task) }); }
      if (path === "/api/invitations/import" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const parsed = z.object({ taskId: z.string().uuid(), filename: z.string().trim().min(1).max(255), fileBase64: z.string().min(1).max(35_000_000) }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); const task = await this.options.store.findInvitationTask(parsed.data.taskId); if (!task || task.createdById !== user.id) return write(response, 404, { error: "not_found" }); let bytes: Buffer; try { bytes = Buffer.from(parsed.data.fileBase64, "base64"); } catch { return write(response, 400, { error: "invalid_import" }); } try { const result = parseInvitationImport(parsed.data.filename, bytes); const record = await this.options.store.createInvitationImport({ invitationTaskId: task.id, uploadedById: user.id, filename: parsed.data.filename, rows: result.rows, totalRows: result.totalRows, validRows: result.validRows, invalidRows: result.invalidRows, duplicateRows: result.duplicateRows }); return write(response, 201, { import: publicInvitationImport(record), preview: { totalRows: result.totalRows, valid: result.validRows, invalid: result.invalidRows, duplicates: result.duplicateRows, issues: result.issues } }); } catch (error) { return write(response, 400, { error: error instanceof Error ? error.message : "invalid_import" }); } }
      if (path === "/api/invitations/imports" && method === "GET") { if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" }); return write(response, 200, { items: (await this.options.store.listInvitationImports(user.id)).map(publicInvitationImport) }); }
      const invitationQueue = path.match(/^\/api\/invitations\/tasks\/([^/]+)\/queue$/); if (invitationQueue && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const taskId = invitationQueue[1]; if (!taskId) return write(response, 404, { error: "not_found" }); const task = await this.options.store.findInvitationTask(taskId); if (!task || task.createdById !== user.id) return write(response, 404, { error: "not_found" }); if (task.userCount === 0) return write(response, 409, { error: "invitation_users_empty" }); const command = createCommandEnvelope({ type: "PROCESS_INVITATION_ITEM", requestedBy: user.id, payload: { invitationTaskId: task.id } }); const receipt = await this.options.commandQueue.enqueue(command); return write(response, 202, { task: publicInvitationTask(task), jobId: receipt.jobId, status: "QUEUED" }); }
      if ((path === "/api/logs" || path === "/api/audit") && method === "GET") {
        if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" });
        const rawLimit = Number(query.get("limit") ?? "50"); const limit = Number.isInteger(rawLimit) && rawLimit > 0 ? Math.min(rawLimit, 100) : 50;
        const beforeRaw = query.get("before"); const beforeDate = beforeRaw ? new Date(beforeRaw) : undefined; const before = beforeDate && !Number.isNaN(beforeDate.getTime()) ? beforeDate : undefined;
        if (path === "/api/logs") {
          const typeRaw = query.get("type"); const levelRaw = query.get("level");
          const type = typeRaw && ["ACCOUNT", "TELEGRAM", "PROXY", "WORKER", "TASK", "INVITATION", "AUTHENTICATION", "SYSTEM"].includes(typeRaw) ? typeRaw as LogType : undefined;
          const level = levelRaw && ["INFO", "WARNING", "ERROR", "CRITICAL"].includes(levelRaw) ? levelRaw as LogLevel : undefined;
          const items = await this.options.store.listLogs(user.id, { ...(type ? { type } : {}), ...(level ? { level } : {}), ...(query.get("accountId") ? { accountId: query.get("accountId")! } : {}), ...(query.get("taskId") ? { taskId: query.get("taskId")! } : {}), ...(query.get("search") ? { search: query.get("search")! } : {}), limit, ...(before ? { before } : {}) });
          return write(response, 200, { items: items.map(publicLog), nextCursor: items.at(-1)?.createdAt.toISOString() ?? null });
        }
        const items = await this.options.store.listAuditLogs(user.id, { ...(query.get("search") ? { search: query.get("search")! } : {}), ...(query.get("entity") ? { entity: query.get("entity")! } : {}), limit, ...(before ? { before } : {}) });
        return write(response, 200, { items: items.map(publicAuditLog), nextCursor: items.at(-1)?.createdAt.toISOString() ?? null });
      }
      const userMutation = path.match(/^\/api\/users\/([^/]+)$/);
      if (userMutation && (method === "PATCH" || method === "DELETE")) {
        if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" });
        const targetId = userMutation[1]; if (!targetId) return write(response, 404, { error: "not_found" }); const target = await this.options.store.findUserById(targetId); if (!target) return write(response, 404, { error: "not_found" });
        if (method === "DELETE") { if (target.id === user.id) return write(response, 409, { error: "cannot_delete_current_user" }); await this.options.store.deleteUser(target.id); await this.audit(user, request, "DELETE", "User", target.id, publicUser(target)); return write(response, 204); }
        const parsed = z.object({ name: z.string().trim().min(1).max(120).nullable().optional(), role: z.enum(roles).optional() }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() });
        const updateInput = { ...(parsed.data.name === undefined ? {} : { name: parsed.data.name }), ...(parsed.data.role === undefined ? {} : { role: parsed.data.role }) }; const updated = await this.options.store.updateUser(target.id, updateInput); await this.audit(user, request, "UPDATE", "User", target.id, publicUser(target), publicUser(updated)); return write(response, 200, { user: publicUser(updated) });
      }
      if (path === "/api/users" && method === "GET") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); write(response, 200, { items: (await this.options.store.listUsers()).map(publicUser) }); return; }
      if (path === "/api/users" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const parsed = userSchema.safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); try { const created = await this.options.store.createUser({ email: parsed.data.email.toLowerCase(), name: parsed.data.name, passwordHash: await hashPassword(parsed.data.password), role: parsed.data.role as RoleName }); await this.audit(user, request, "CREATE", "User", created.id, undefined, publicUser(created)); write(response, 201, { user: publicUser(created) }); } catch (error) { if (error instanceof Error && error.message === "USER_EMAIL_EXISTS") return write(response, 409, { error: "email_exists" }); throw error; } return; }
      if ((path === "/api/accounts/connect/request" || path === "/api/accounts/connect") && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const parsed = z.object({ phone: z.string().trim().min(5).max(40), proxyId: z.string().uuid().optional(), accountGroupId: z.string().uuid().optional() }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); if (parsed.data.proxyId && !(await this.options.store.findProxy(parsed.data.proxyId))) return write(response, 400, { error: "proxy_not_found" }); const account = await this.options.store.createAccount({ ownerId: user.id, phone: parsed.data.phone, ...(parsed.data.proxyId === undefined ? {} : { proxyId: parsed.data.proxyId }) }); const command = createCommandEnvelope({ type: "CONNECT_ACCOUNT", accountId: account.id, requestedBy: user.id, payload: { phone: parsed.data.phone, proxyId: parsed.data.proxyId, accountGroupId: parsed.data.accountGroupId, phase: "request_code" } }); const receipt = await this.options.commandQueue.enqueue(command); await this.options.store.updateAccount(account.id, { status: "CONNECTING" }); return write(response, 202, { account: publicAccount({ ...account, status: "CONNECTING" }, account.proxyId ? await this.options.store.findProxy(account.proxyId) : undefined), jobId: receipt.jobId }); }
      const verifyMatch = path.match(/^\/api\/accounts\/([^/]+)\/(?:connect\/)?verify$/); if (verifyMatch && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const account = await this.options.store.findAccount(verifyMatch[1]); if (!account || account.ownerId !== user.id) return write(response, 404, { error: "not_found" }); const parsed = z.object({ code: z.string().trim().min(1).max(32), twoFactorPassword: z.string().max(256).optional() }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); const command = createCommandEnvelope({ type: "CONNECT_ACCOUNT", accountId: account.id, requestedBy: user.id, payload: { code: parsed.data.code, ...(parsed.data.twoFactorPassword === undefined ? {} : { encryptedTwoFactorPassword: encrypt(parsed.data.twoFactorPassword, this.securityKey) }), phase: "verify_code" } }); const receipt = await this.options.commandQueue.enqueue(command); return write(response, 202, { account: publicAccount(account), jobId: receipt.jobId }); }
      const disconnectMatch = path.match(/^\/api\/accounts\/([^/]+)\/disconnect$/); if (disconnectMatch && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const account = await this.options.store.findAccount(disconnectMatch[1]); if (!account || account.ownerId !== user.id) return write(response, 404, { error: "not_found" }); const command = createCommandEnvelope({ type: "DISCONNECT_ACCOUNT", accountId: account.id, requestedBy: user.id, payload: {} }); const receipt = await this.options.commandQueue.enqueue(command); return write(response, 202, { account: publicAccount(account), jobId: receipt.jobId }); }
      if (path === "/api/accounts" && method === "GET") { if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" }); let accounts = [...await this.options.store.listAccounts(user.id)]; const status = query.get("status"); const search = query.get("search")?.toLowerCase(); if (status) accounts = accounts.filter((a) => a.status === status); if (search) accounts = accounts.filter((a) => `${a.username ?? ""} ${a.phone ?? ""} ${a.telegramId?.toString() ?? ""} ${a.id}`.toLowerCase().includes(search)); const items = await Promise.all(accounts.map(async (a) => publicAccount(a, a.proxyId ? await this.options.store.findProxy(a.proxyId) : undefined))); write(response, 200, { items }); return; }
      if (path === "/api/accounts" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const parsed = accountSchema.safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); if (parsed.data.proxyId && !(await this.options.store.findProxy(parsed.data.proxyId))) return write(response, 400, { error: "proxy_not_found" }); const account = await this.options.store.createAccount({ ownerId: user.id, ...parsed.data, ...(parsed.data.telegramId === undefined ? {} : { telegramId: BigInt(parsed.data.telegramId) }) }); await this.audit(user, request, "CREATE", "TelegramAccount", account.id, undefined, publicAccount(account)); write(response, 201, { account: publicAccount(account, account.proxyId ? await this.options.store.findProxy(account.proxyId) : undefined) }); return; }
      const accountMatch = path.match(/^\/api\/accounts\/([^/]+)$/); if (accountMatch && method === "PATCH") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const account = await this.options.store.findAccount(accountMatch[1]); if (!account || account.ownerId !== user.id) return write(response, 404, { error: "not_found" }); const parsed = z.object({ status: z.enum(accountStatuses).optional(), username: z.string().trim().max(120).optional(), phone: z.string().trim().max(40).optional(), firstName: z.string().trim().max(120).optional(), lastName: z.string().trim().max(120).optional(), avatarUrl: z.string().url().optional(), proxyId: z.string().uuid().nullable().optional() }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); const updated = await this.options.store.updateAccount(account.id, parsed.data as { status?: TelegramAccountStatus; proxyId?: string | null }); write(response, 200, { account: publicAccount(updated, updated.proxyId ? await this.options.store.findProxy(updated.proxyId) : undefined) }); return; }
      if (path === "/api/proxies" && method === "GET") { if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" }); write(response, 200, { items: (await this.options.store.listProxies()).map(publicProxy) }); return; }
      if (path === "/api/proxies" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const parsed = proxySchema.safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); try { const proxy = await this.options.store.createProxy({ ...parsed.data, protocol: parsed.data.protocol as ProxyProtocol, ...(parsed.data.username === undefined ? {} : { encryptedUsername: encrypt(parsed.data.username, this.securityKey) }), ...(parsed.data.password === undefined ? {} : { encryptedPassword: encrypt(parsed.data.password, this.securityKey) }) }); await this.audit(user, request, "CREATE", "Proxy", proxy.id, undefined, publicProxy(proxy)); write(response, 201, { proxy: publicProxy(proxy) }); } catch (error) { if (error instanceof Error && error.message === "PROXY_EXISTS") return write(response, 409, { error: "proxy_exists" }); throw error; } return; }
      if (path === "/api/proxies/import" && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const parsed = z.object({ protocol: z.enum(proxyProtocols), text: z.string().max(1_000_000) }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); let created = 0; let invalid = 0; for (const line of parsed.data.text.split(/\r?\n/)) { const item = parseProxyLine(line); if (!item) { if (line.trim() !== "" && !line.trim().startsWith("#")) invalid += 1; continue; } try { await this.options.store.createProxy({ name: `${item.host}:${item.port}`, host: item.host, port: item.port, protocol: parsed.data.protocol as ProxyProtocol, ...(item.username === undefined ? {} : { encryptedUsername: encrypt(item.username, this.securityKey) }), ...(item.password === undefined ? {} : { encryptedPassword: encrypt(item.password, this.securityKey) }) }); created += 1; } catch (error) { if (!(error instanceof Error && error.message === "PROXY_EXISTS")) throw error; } } return write(response, 201, { created, invalid }); }
      const proxyMatch = path.match(/^\/api\/proxies\/([^/]+)$/); if (proxyMatch && method === "PATCH") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const current = await this.options.store.findProxy(proxyMatch[1]); if (!current) return write(response, 404, { error: "not_found" }); const parsed = proxySchema.partial().safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); const updated = await this.options.store.updateProxy(current.id, { ...parsed.data, ...(parsed.data.username === undefined ? {} : { encryptedUsername: encrypt(parsed.data.username, this.securityKey) }), ...(parsed.data.password === undefined ? {} : { encryptedPassword: encrypt(parsed.data.password, this.securityKey) }) }); return write(response, 200, { proxy: publicProxy(updated) }); }
      if (proxyMatch && method === "GET") { if (!this.allowed(user, "read")) return write(response, 403, { error: "permission_denied" }); const current = await this.options.store.findProxy(proxyMatch[1]); if (!current) return write(response, 404, { error: "not_found" }); return write(response, 200, { proxy: publicProxy(current) }); }
      if (proxyMatch && method === "DELETE") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const current = await this.options.store.findProxy(proxyMatch[1]); if (!current) return write(response, 404, { error: "not_found" }); await this.options.store.deleteProxy(current.id); return write(response, 204); }
      const disableMatch = path.match(/^\/api\/proxies\/([^/]+)\/disable$/); if (disableMatch && method === "POST") { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const current = await this.options.store.findProxy(disableMatch[1]); if (!current) return write(response, 404, { error: "not_found" }); const updated = await this.options.store.updateProxy(current.id, { status: "DISABLED", disabledAt: new Date() }); return write(response, 200, { proxy: publicProxy(updated) }); }
      const testAll = path === "/api/proxies/test-all" && method === "POST"; const testMatch = path.match(/^\/api\/proxies\/([^/]+)\/test$/); if (testAll || testMatch) { if (!this.allowed(user, "manage")) return write(response, 403, { error: "permission_denied" }); const checker = this.options.proxyChecker ?? new NetworkProxyChecker(); const proxies = testAll ? await this.options.store.listProxies() : [await this.options.store.findProxy(testMatch?.[1])].filter((value): value is StoredProxy => value !== undefined); if (proxies.length === 0) return write(response, 404, { error: "not_found" }); const results: Array<ProxyCheckResult & { readonly id: string }> = []; for (const proxy of proxies) { const username = decrypt(proxy.encryptedUsername, this.securityKey); const password = decrypt(proxy.encryptedPassword, this.securityKey); const result = await checker.check({ id: proxy.id, host: proxy.host, port: proxy.port, protocol: proxy.protocol, ...(username === undefined ? {} : { username }), ...(password === undefined ? {} : { password }) }); await this.options.store.updateProxy(proxy.id, { status: result.status, pingMs: result.pingMs ?? null, errorCode: result.errorCode ?? null, lastCheckedAt: new Date() }); results.push({ id: proxy.id, ...result }); } const first = proxies[0]!; return write(response, 200, testAll ? { results } : { proxy: publicProxy((await this.options.store.findProxy(first.id))!) }); }
      write(response, 404, { error: "not_found" });
    } catch (error) { if (error instanceof Error && error.message === "INVALID_JSON") return write(response, 400, { error: "invalid_json" }); if (process.env.NODE_ENV !== "production") console.error(error instanceof Error ? error.message : "internal error"); write(response, 500, { error: "internal_error" }); }
  }
  private get securityKey(): Buffer { return this.options.security.encryptionKey ?? Buffer.alloc(32, 1); }
  private allowed(user: StoredUser, permission: "read" | "manage"): boolean { return user.roles.some((role) => can(role, permission)); }
  private async audit(user: StoredUser, request: IncomingMessage, action: string, entity: string, entityId?: string, before?: unknown, after?: unknown): Promise<void> {
    const role = user.roles[0]; const ipAddress = request.socket.remoteAddress;
    await this.options.store.createAuditLog({ actorId: user.id, ...(role === undefined ? {} : { role }), ...(ipAddress === undefined ? {} : { ipAddress }), action, entity, ...(entityId ? { entityId } : {}), ...(before === undefined ? {} : { before: redact(before) as Prisma.InputJsonValue }), ...(after === undefined ? {} : { after: redact(after) as Prisma.InputJsonValue }) });
    this.options.eventHub?.publish({ type: "audit", entity, ...(entityId ? { entityId } : {}), payload: { action, actorId: user.id }, createdAt: new Date().toISOString() });
  }
  private async currentUser(request: IncomingMessage): Promise<StoredUser | undefined> { const header = request.headers.authorization; return this.options.security.authenticateAccess(header?.startsWith("Bearer ") ? header.slice(7) : undefined); }
  private async auth(method: string, action: string, request: IncomingMessage, response: ServerResponse): Promise<void> {
    if (action === "register" && method === "POST") { const parsed = registerSchema.safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error", details: parsed.error.flatten() }); if (await this.options.store.countUsers() > 0) return write(response, 409, { error: "registration_closed" }); const user = await this.options.store.createUser({ email: parsed.data.email.toLowerCase(), name: parsed.data.name, passwordHash: await hashPassword(parsed.data.password), role: "OWNER" }); return this.tokens(response, user, 201); }
    if (action === "login" && method === "POST") { const parsed = loginSchema.safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error" }); const user = await this.options.store.findUserByEmail(parsed.data.email.toLowerCase()); if (!user || !(await verifyPassword(parsed.data.password, user.passwordHash))) return write(response, 401, { error: "invalid_credentials" }); return this.tokens(response, user); }
    if (action === "refresh" && method === "POST") { const parsed = z.object({ refreshToken: z.string().min(1) }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error" }); const rotated = await this.options.security.rotateRefresh(parsed.data.refreshToken); if (!rotated) return write(response, 401, { error: "invalid_refresh_token" }); return write(response, 200, { user: publicUser(rotated.user), accessToken: rotated.accessToken, refreshToken: rotated.refreshToken }); }
    if (action === "logout" && method === "POST") { const user = await this.currentUser(request); if (!user) return write(response, 401, { error: "authentication_required" }); await this.options.store.revokeSessionsForUser(user.id); this.options.security.invalidateUser(user.id); return write(response, 204); }
    if (action === "me" && method === "GET") { const user = await this.currentUser(request); if (!user) return write(response, 401, { error: "authentication_required" }); return write(response, 200, { user: publicUser(user) }); }
    if (action === "forgot-password" && method === "POST") { const parsed = z.object({ email: z.string().email() }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error" }); const user = await this.options.store.findUserByEmail(parsed.data.email.toLowerCase()); if (user) { const token = this.options.security.issueResetToken(); await this.options.store.createResetToken(this.options.security.hashToken(token), user.id, new Date(Date.now() + this.options.security.resetTtlSeconds * 1000)); const message: PasswordResetMessage = { email: user.email, token }; await this.options.passwordResetNotifier.send(message); } return write(response, 202, { accepted: true }); }
    if (action === "reset-password" && method === "POST") { const parsed = z.object({ token: z.string().min(1), password: z.string().min(12).max(200) }).safeParse(await body(request)); if (!parsed.success) return write(response, 400, { error: "validation_error" }); const reset = await this.options.store.findResetToken(this.options.security.hashToken(parsed.data.token)); if (!reset || reset.usedAt || reset.expiresAt <= new Date()) return write(response, 401, { error: "invalid_reset_token" }); await this.options.store.updateUserPassword(reset.userId, await hashPassword(parsed.data.password)); await this.options.store.consumeResetToken(reset.tokenHash); await this.options.store.revokeSessionsForUser(reset.userId); return write(response, 204); }
    return write(response, 404, { error: "not_found" });
  }
  private async tokens(response: ServerResponse, user: StoredUser, status = 200): Promise<void> { this.options.security.clearInvalidation(user.id); const accessToken = this.options.security.issueAccessToken(user.id); const refreshToken = this.options.security.issueRefreshToken(user.id); await this.options.store.createSession(user.id, this.options.security.hashToken(refreshToken), new Date(Date.now() + 86_400_000)); write(response, status, { user: publicUser(user), accessToken, refreshToken }); }
}
