import { zipSync, unzipSync } from "fflate";

export type TDataImportErrorCode = "invalid_filename" | "archive_too_large" | "invalid_archive" | "archive_too_many_files" | "archive_too_large_uncompressed" | "invalid_tdata_structure" | "unsupported_tdata_format";
export class TDataImportError extends Error { public constructor(public readonly code: TDataImportErrorCode) { super(code); this.name = "TDataImportError"; } }
export interface TDataInspection { readonly filename: string; readonly entries: readonly string[]; readonly accountHint: string | undefined; }
export interface TDataConverterInput { readonly accountHint: string | undefined; readonly entries: readonly { readonly path: string; readonly data: Uint8Array }[]; }
export interface TDataConversionProfile { readonly telegramId: bigint | string | number; readonly username?: string | undefined; readonly phone?: string | undefined; readonly firstName?: string | undefined; readonly lastName?: string | undefined; readonly avatar?: string | undefined; }
export interface TDataConversionResult { readonly session: string; readonly profile: TDataConversionProfile; }
export interface TDataConverter { convert(input: TDataConverterInput): Promise<TDataConversionResult>; }
export interface TDataImportOptions { readonly converter?: TDataConverter | undefined; readonly maxArchiveBytes?: number; readonly maxUncompressedBytes?: number; readonly maxEntries?: number; }
export interface TDataImportResult { readonly filename: string; readonly profile: { readonly telegramId: string; readonly username?: string | undefined; readonly phone?: string | undefined; readonly firstName?: string | undefined; readonly lastName?: string | undefined; readonly avatar?: string | undefined; }; }
export interface TDataImporter { inspect(archive: Uint8Array, filename: string, accountHint?: string): Promise<TDataInspection>; import(archive: Uint8Array, filename: string, options?: { readonly accountHint?: string }): Promise<TDataImportResult>; createTestArchive(paths: readonly string[]): { readonly archive: Uint8Array }; }
const defaultMaxArchiveBytes = 25 * 1024 * 1024; const defaultMaxUncompressedBytes = 100 * 1024 * 1024; const defaultMaxEntries = 2_000;
function safeFilename(filename: string): string { const value = filename.trim(); if (!value.toLowerCase().endsWith(".zip") || value.length > 255 || value.includes("\\") || value.includes("/") || value.includes("\0")) throw new TDataImportError("invalid_filename"); return value; }
function safeEntryPath(path: string): string { const normalized = path.replaceAll("\\", "/"); if (normalized.startsWith("/") || normalized.includes("\0") || normalized.split("/").some((segment) => segment === "..")) throw new TDataImportError("invalid_archive"); return normalized.replace(/^\.\//, ""); }
function isTDataStructure(entries: readonly string[]): boolean { const names = entries.map((entry) => entry.toLowerCase()); return names.some((entry) => entry === "key_datas" || entry.endsWith("/key_datas")) && names.some((entry) => /(?:^|\/)map\d+$/.test(entry)); }
function accountHintFromEntries(entries: readonly string[]): string | undefined { const root = entries.find((entry) => entry.toLowerCase().endsWith("/key_datas")); return root?.split("/").slice(-2, -1)[0]; }
export function createTDataImporter(options: TDataImportOptions = {}): TDataImporter {
  const maxArchiveBytes = options.maxArchiveBytes ?? defaultMaxArchiveBytes; const maxUncompressedBytes = options.maxUncompressedBytes ?? defaultMaxUncompressedBytes; const maxEntries = options.maxEntries ?? defaultMaxEntries;
  async function inspect(archive: Uint8Array, filename: string, accountHint?: string): Promise<TDataInspection> { const safeName = safeFilename(filename); if (archive.byteLength > maxArchiveBytes) throw new TDataImportError("archive_too_large"); let files: Record<string, Uint8Array>; try { files = unzipSync(archive); } catch { throw new TDataImportError("invalid_archive"); } const rawEntries = Object.keys(files); const entries = rawEntries.map(safeEntryPath); if (entries.length > maxEntries) throw new TDataImportError("archive_too_many_files"); let totalBytes = 0; for (const path of rawEntries) { totalBytes += files[path]?.byteLength ?? 0; if (totalBytes > maxUncompressedBytes) throw new TDataImportError("archive_too_large_uncompressed"); } if (!isTDataStructure(entries)) throw new TDataImportError("invalid_tdata_structure"); return { filename: safeName, entries, accountHint: accountHint ?? accountHintFromEntries(entries) }; }
  return { inspect, import: async (archive, filename, importOptions = {}) => { const inspection = await inspect(archive, filename, importOptions.accountHint); if (!options.converter) throw new TDataImportError("unsupported_tdata_format"); let files: Record<string, Uint8Array>; try { files = unzipSync(archive); } catch { throw new TDataImportError("invalid_archive"); } const entries = Object.entries(files).map(([path, data]) => ({ path: safeEntryPath(path), data })); const converted = await options.converter.convert({ accountHint: inspection.accountHint, entries }); if (!converted.session || !converted.profile.telegramId) throw new TDataImportError("unsupported_tdata_format"); return { filename: inspection.filename, profile: { telegramId: String(converted.profile.telegramId), ...(converted.profile.username === undefined ? {} : { username: converted.profile.username }), ...(converted.profile.phone === undefined ? {} : { phone: converted.profile.phone }), ...(converted.profile.firstName === undefined ? {} : { firstName: converted.profile.firstName }), ...(converted.profile.lastName === undefined ? {} : { lastName: converted.profile.lastName }), ...(converted.profile.avatar === undefined ? {} : { avatar: converted.profile.avatar }) } }; }, createTestArchive: (paths) => ({ archive: zipSync(Object.fromEntries(paths.map((path) => [path, new Uint8Array([1])]))) }) };
}
