"use client";
import { useEffect, useState } from "react";
import { createApiClient } from "@/services/api-client";
type ProxyItem = { readonly id: string; readonly name: string; readonly host: string; readonly port: number; readonly protocol: string; readonly status: string; readonly pingMs?: number | null };
export default function ProxiesPage() {
  const [items, setItems] = useState<readonly ProxyItem[]>([]); const [protocol, setProtocol] = useState("SOCKS5"); const [form, setForm] = useState({ name:"", host:"", port:"", username:"", password:"", country:"" }); const [bulk, setBulk] = useState(""); const [status, setStatus] = useState(""); const api = createApiClient();
  async function load() { try { const r = await api.get<{readonly items: readonly ProxyItem[]}>("/api/proxies"); setItems(r.items); setStatus(r.items.length + " прокси"); } catch (e) { setStatus(e instanceof Error ? e.message : "Не удалось загрузить прокси"); } }
  useEffect(() => { void load(); }, []);
  async function create() { try { await api.post("/api/proxies", { ...form, port:Number(form.port), protocol }); setStatus("Прокси добавлен"); setForm({name:"",host:"",port:"",username:"",password:"",country:""}); await load(); } catch (e) { setStatus(e instanceof Error ? e.message : "Не удалось добавить прокси"); } }
  async function importBulk() { try { const r = await api.post<{readonly created:number;readonly invalid:number}>("/api/proxies/import", { protocol, text:bulk }); setStatus("Импортировано: " + r.created + "; пропущено: " + r.invalid); setBulk(""); await load(); } catch (e) { setStatus(e instanceof Error ? e.message : "Не удалось импортировать список"); } }
  async function test(id?: string) { try { const r = await api.post<{readonly results?: readonly unknown[]}>(id ? "/api/proxies/" + id + "/test" : "/api/proxies/test-all", {}); setStatus(id ? "Проверка завершена" : "Проверено: " + (r.results?.length ?? 0)); await load(); } catch (e) { setStatus(e instanceof Error ? e.message : "Проверка не удалась"); } }
  async function remove(id:string) { if (!window.confirm("Удалить прокси?")) return; try { await api.delete("/api/proxies/" + id); await load(); } catch (e) { setStatus(e instanceof Error ? e.message : "Не удалось удалить прокси"); } }
  const update = (key:keyof typeof form) => (e:React.ChangeEvent<HTMLInputElement>) => setForm(c => ({...c, [key]:e.target.value}));
  return <div className="space-y-6"><div><p className="eyebrow">Network / Proxies</p><h1 className="mt-2 text-3xl font-semibold text-white">Прокси</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Добавляйте SOCKS5, HTTP и HTTPS прокси. Пароли шифруются backend.</p></div><section className="surface-card grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-4">{(["name","host","port","username","password","country"] as const).map(k => <label key={k} className="text-xs text-slate-400">{k}<input type={k === "password" ? "password" : k === "port" ? "number" : "text"} value={form[k]} onChange={update(k)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-white" /></label>)}<label className="text-xs text-slate-400">protocol<select value={protocol} onChange={e=>setProtocol(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-white"><option>SOCKS5</option><option>HTTP</option><option>HTTPS</option></select></label><div className="flex items-end gap-2"><button type="button" onClick={()=>void create()} className="min-h-11 rounded-lg bg-emerald-300 px-4 text-sm font-semibold text-slate-950">Добавить</button><button type="button" onClick={()=>void test()} className="min-h-11 rounded-lg border border-slate-700 px-4 text-sm text-slate-200">Проверить все</button></div></section><section className="surface-card space-y-3 p-5"><h2 className="font-medium text-slate-200">Импорт списка</h2><p className="text-xs text-slate-500">Одна строка: host:port или user:password@host:port</p><textarea value={bulk} onChange={e=>setBulk(e.target.value)} rows={4} className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 font-mono text-sm text-white" /><button type="button" onClick={()=>void importBulk()} disabled={!bulk.trim()} className="min-h-11 rounded-lg border border-emerald-300/40 px-4 text-sm text-emerald-200 disabled:opacity-50">Импортировать</button></section>{status ? <p role="status" className="text-sm text-slate-400">{status}</p> : null}<section className="surface-card divide-y divide-slate-800">{items.length === 0 ? <p className="p-6 text-sm text-slate-500">Прокси пока не добавлены.</p> : items.map(i => <article key={i.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><h2 className="font-medium text-slate-200">{i.name}</h2><p className="font-mono text-xs text-slate-500">{i.protocol} · {i.host}:{i.port} · {i.status}{i.pingMs ? " · " + i.pingMs + " ms" : ""}</p></div><div className="flex gap-2"><button type="button" onClick={()=>void test(i.id)} className="min-h-10 rounded border border-slate-700 px-3 text-xs text-slate-200">Проверить</button><button type="button" onClick={()=>void remove(i.id)} className="min-h-10 rounded border border-red-400/40 px-3 text-xs text-red-200">Удалить</button></div></article>)}</section></div>;
}
